"""Read-only API for documentation generated by the agent workflow."""

import base64
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel

from app.core.config import settings

router = APIRouter()


class GeneratedDocumentSummary(BaseModel):
    """Metadata displayed in the frontend documentation dashboard."""

    id: str
    repo_id: str
    title: str
    source_path: str
    status: str = "pending_review"
    created_at: str


class GeneratedDocument(GeneratedDocumentSummary):
    """A generated Markdown document and its display metadata."""

    content: str


def _documents_root() -> Path:
    return settings.generated_docs_path_dir.resolve()


def _document_id(relative_path: Path) -> str:
    encoded = base64.urlsafe_b64encode(relative_path.as_posix().encode("utf-8"))
    return encoded.decode("ascii").rstrip("=")


def _relative_path(document_id: str) -> Path:
    try:
        padded = document_id + "=" * (-len(document_id) % 4)
        decoded = base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
    except (UnicodeDecodeError, ValueError) as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found") from exc

    path = Path(decoded)
    if path.is_absolute() or ".." in path.parts or path.suffix.lower() != ".md":
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")
    return path


def _summary(path: Path, root: Path) -> GeneratedDocumentSummary:
    relative_path = path.relative_to(root)
    stat = path.stat()
    repo_id = relative_path.parts[0] if relative_path.parts else "unknown"
    title = relative_path.with_suffix("").as_posix()

    return GeneratedDocumentSummary(
        id=_document_id(relative_path),
        repo_id=repo_id,
        title=title,
        source_path=relative_path.as_posix(),
        created_at=datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
    )


@router.get("", response_model=list[GeneratedDocumentSummary])
async def list_generated_documents() -> list[GeneratedDocumentSummary]:
    """List every Markdown document written by the Sync Agent."""
    root = _documents_root()
    if not root.exists():
        return []

    documents = [
        _summary(path, root)
        for path in root.rglob("*.md")
        if path.is_file()
    ]
    return sorted(documents, key=lambda document: document.created_at, reverse=True)


@router.get("/content", response_model=GeneratedDocument)
async def get_generated_document(
    document_id: str = Query(..., alias="id"),
) -> GeneratedDocument:
    """Return one generated Markdown document by its opaque API identifier."""
    root = _documents_root()
    relative_path = _relative_path(document_id)
    document_path = (root / relative_path).resolve()

    if root not in document_path.parents or not document_path.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found")

    try:
        content = document_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Generated document could not be read",
        ) from exc

    return GeneratedDocument(**_summary(document_path, root).model_dump(), content=content)
